insert into items (item_type_cod,designation,price)
values ('1','Canapés','5'),
('1','Tábua de Enchidos','10'),
('1','Tábua de Queijos','10'),
('1','Pão e Manteiga','2,5'),
('1','Tábua de Carnes Frias','10'),
('1','Azeitonas','2,5'),
('1','Salada','1,5'),
('2','Rancho à Portuguesa','7,5'),
('2','Feijoada Transmontana','7,5'),
('2','Carne de Porno à Alentejana','7,5'),
('2','Prego no Prato','8,5'),
('2','Francesinha','10'),
('2','Cozido à Portuguesa','7,5'),
('3','Atum Grelhado com Sementes','12,5'),
('3','Bacalhau com Natas','7,5'),
('3','Bacalhau à Brás','7,5'),
('3','Salmão Grelhado com Sementes','12,5'),
('3','Massada de Peixe','10'),
('3','Massada de Garoupa','10'),
('4','Arroz, Batata e Ovos','5'),
('4','Ovos Verdes','5'),
('4','Ovo à Brás','5'),
('5','Beringela Recheada','10'),
('5','Tarteletes de Cogumelos','10'),
('5','Tortilha de Legumes','10'),
('5','Soja à Brás','10'),
('6','Vinho Tinto','4,6'),
('6','Vinho Branco','4,5'),
('6','Vinho Rosé','5'),
('6','Cerveja','1,70'),
('6','Água','1,00'),
('6','Coca-Cola/Pepsi','1,70'),
('6','Ice tea','1,70'),
('6','Fanta/Sumol','1,70')


